
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Dec 11 2025 13:09:04 EST (Dec 11 2025 18:09:04 UTC)

// Verification Directory fv/alu_1bit 

module alu_1bit(Ai, Bi, A_prev, A_next, Cini, sel, Fi, Couti);
  input Ai, Bi, A_prev, A_next, Cini;
  input [3:0] sel;
  output Fi, Couti;
  wire Ai, Bi, A_prev, A_next, Cini;
  wire [3:0] sel;
  wire Fi, Couti;
  wire Di, Ei, n_0, shift_left, shift_right;
  arithmetic_unit U_ARITH(.Ai (Ai), .Bi (Bi), .Cini (Cini), .sel
       (sel[1:0]), .Di (Di), .Couti (Couti));
  logic_unit U_LOGIC(.Ai (Ai), .Bi (Bi), .sel (sel[1:0]), .Ei (Ei));
  mux4to1 U_MUX(.a (Di), .b (Ei), .c (shift_right), .d (shift_left),
       .sel (sel[3:2]), .out (Fi));
  NOR2XL g55__2398(.A (sel[2]), .B (n_0), .Y (shift_right));
  AND3XL g56__5107(.A (sel[3]), .B (sel[2]), .C (A_next), .Y
       (shift_left));
  NAND2XL g57__6260(.A (sel[3]), .B (A_prev), .Y (n_0));
endmodule

